spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://mysql:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul
    username: user
    password: password

jwt:
  secret: q0lD+q8c9FArv3Ht1XG1MPnY0GjMRn0jVt9mCln9EclZdfXc7fLOhM5U8H8K6U5qQBr8Qm/JyB8VfdyhxXYuNA==
